name: Deploy to nais
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
    secrets:
      NAIS_DEPLOY_APIKEY:
        required: true

jobs:
  deploy:
    name: Deploy configmap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Validate Task Analytics config
        uses: walbo/validate-json@v1.1.0
        with:
          files: configs/${{ inputs.env }}/ta-config.json
          schema: schemas/ta-config.schema.json
          fail-on-missing-schema: true
          schema-version: draft-07
          strict: false
      - name: Read json files
        run: |
          echo TA_CONFIG=$(cat ./configs/${{ inputs.env }}/ta-config.json | tr '\n' ' ') >> $GITHUB_ENV
      - name: Inject json into nais-config
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{TA_CONFIG}}"
          replace: ${{env.TA_CONFIG}}
          include: ".nais/config.yml"
      - uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: ${{ inputs.env }}-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config.yml