name: Deploy dev configmap
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - configs/dev/**/*.json

jobs:
  deploy:
    name: Deploy dev configmap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Validate TS config
        uses: walbo/validate-json@v1.1.0
        with:
          files: configs/dev/ta-config.json
          schema: schemas/ta-config.schema.json
          fail-on-missing-schema: true
          schema-version: draft-07
          strict: false
      - name: Set vars
        run: |
          echo TA_CONFIG=$(cat ./configs/dev/ta-config.json | tr '\n' ' ') >> $GITHUB_ENV
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{TA_CONFIG}}"
          replace: ${{env.TA_CONFIG}}
          include: ".nais/config-dev.yml"
      - name: Print yml
        run: |
          echo "$(cat .nais/config-dev.yml)"
      - uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config-dev.yml