name: Deploy dev configmap
on:
  workflow_dispatch:
  push:
    paths:
      - .nais/config-dev.yml
      - dev/**

jobs:
  deploy:
    name: Deploy dev configmap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config-dev.yml
          VAR: TS_CONFIG=$(cat ./dev/ta-config.json)