name: Deploy dev configmap
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy dev configmap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set vars
        run: |
          echo 'TS_CONFIG<<EOF' >> $GITHUB_ENV
          cat ./dev/ta-config.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config-dev.yml
          VAR: TS_CONFIG=${{ env.TS_CONFIG }}